# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_analyze.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_analyze_form(object):
    def setupUi(self, analyze_form):
        analyze_form.setObjectName("analyze_form")
        analyze_form.resize(984, 1010)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(analyze_form.sizePolicy().hasHeightForWidth())
        analyze_form.setSizePolicy(sizePolicy)
        analyze_form.setStyleSheet("#frame{\n"
"    background-color: rgb(37, 64, 83);    \n"
"}\n"
"#frame_top_2{\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"  border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"QTextEdit{\n"
"    background-color: rgb(237, 243, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"    width: 15px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background:  rgb(37, 64, 83);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"#frame_4{\n"
"    background-color: rgb(237, 243, 255);\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(analyze_form)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_1 = QtWidgets.QFrame(analyze_form)
        self.frame_1.setStyleSheet("")
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_top_2 = QtWidgets.QFrame(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_2.sizePolicy().hasHeightForWidth())
        self.frame_top_2.setSizePolicy(sizePolicy)
        self.frame_top_2.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_top_2.setMaximumSize(QtCore.QSize(16777215, 36))
        self.frame_top_2.setSizeIncrement(QtCore.QSize(0, 36))
        self.frame_top_2.setBaseSize(QtCore.QSize(0, 36))
        self.frame_top_2.setMouseTracking(False)
        self.frame_top_2.setStyleSheet("")
        self.frame_top_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_2.setObjectName("frame_top_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_top_2)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.label_24 = QtWidgets.QLabel(self.frame_top_2)
        self.label_24.setMinimumSize(QtCore.QSize(20, 20))
        self.label_24.setMaximumSize(QtCore.QSize(20, 20))
        self.label_24.setStyleSheet("")
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/icon/res/logo.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.frame_top_2)
        self.label_25.setMinimumSize(QtCore.QSize(32, 36))
        self.label_25.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel\n"
"{\n"
"border-radius: 5px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"color: #FFFFFF;\n"
"line-height: 18px;\n"
"font-weight: 400;\n"
"padding-bottom:2px;\n"
"}")
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.pbhide_5 = QtWidgets.QPushButton(self.frame_top_2)
        self.pbhide_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pbhide_5.setMaximumSize(QtCore.QSize(25, 25))
        self.pbhide_5.setMouseTracking(False)
        self.pbhide_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbhide_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbhide_5.setIcon(icon)
        self.pbhide_5.setIconSize(QtCore.QSize(20, 20))
        self.pbhide_5.setObjectName("pbhide_5")
        self.horizontalLayout_13.addWidget(self.pbhide_5)
        self.pbClose_5 = QtWidgets.QPushButton(self.frame_top_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClose_5.sizePolicy().hasHeightForWidth())
        self.pbClose_5.setSizePolicy(sizePolicy)
        self.pbClose_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pbClose_5.setMaximumSize(QtCore.QSize(25, 25))
        self.pbClose_5.setMouseTracking(True)
        self.pbClose_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbClose_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClose_5.setIcon(icon1)
        self.pbClose_5.setIconSize(QtCore.QSize(20, 20))
        self.pbClose_5.setFlat(False)
        self.pbClose_5.setObjectName("pbClose_5")
        self.horizontalLayout_13.addWidget(self.pbClose_5)
        self.label_26 = QtWidgets.QLabel(self.frame_top_2)
        self.label_26.setMinimumSize(QtCore.QSize(1, 0))
        self.label_26.setMaximumSize(QtCore.QSize(1, 16777215))
        self.label_26.setMouseTracking(True)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.verticalLayout_11.addWidget(self.frame_top_2)
        self.frame = QtWidgets.QFrame(self.frame_1)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_2.setStyleSheet("font: 75 14pt \"思源黑体 CN Bold\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(250,250,250);    \n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px; \n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setMinimumSize(QtCore.QSize(30, 30))
        self.label_29.setMaximumSize(QtCore.QSize(30, 30))
        self.label_29.setStyleSheet("border: 1px solid white;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px; \n"
"background-color:#FFFFFF;\n"
"\n"
"")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/icon/res/日历.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_11.addWidget(self.label_29)
        self.lineEdit_time_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_time_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_time_3.setMaximumSize(QtCore.QSize(120, 30))
        self.lineEdit_time_3.setStyleSheet("border:none;\n"
"padding-left: 20px;")
        self.lineEdit_time_3.setObjectName("lineEdit_time_3")
        self.horizontalLayout_11.addWidget(self.lineEdit_time_3)
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setStyleSheet("\n"
"font: 75 9pt \"思源黑体 CN Bold\";")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.lineEdit_time_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_time_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_time_4.setMaximumSize(QtCore.QSize(120, 30))
        self.lineEdit_time_4.setStyleSheet("border:none;\n"
"padding-left: 20px;")
        self.lineEdit_time_4.setText("")
        self.lineEdit_time_4.setObjectName("lineEdit_time_4")
        self.horizontalLayout_11.addWidget(self.lineEdit_time_4)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setMinimumSize(QtCore.QSize(30, 30))
        self.label_32.setMaximumSize(QtCore.QSize(30, 30))
        self.label_32.setStyleSheet("border: 1px solid white;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px; \n"
"background-color:#FFFFFF;")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap(":/icon/res/搜索删除.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32)
        self.horizontalLayout.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.comboBox_9 = QtWidgets.QComboBox(self.frame)
        self.comboBox_9.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout.addWidget(self.comboBox_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.comboBox_10 = QtWidgets.QComboBox(self.frame)
        self.comboBox_10.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout.addWidget(self.comboBox_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"思源黑体 CN Bold\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"思源黑体 CN Bold\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.frame_1)
        self.frame_4.setStyleSheet("")
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setStyleSheet("background-color: rgb(37, 64, 83);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 pt \"思源黑体 CN Bold\";\n"
"padding-left:10px;\n"
"border-radius:3px;\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, 7, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setMinimumSize(QtCore.QSize(10, 10))
        self.label_7.setMaximumSize(QtCore.QSize(10, 10))
        self.label_7.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:2px;")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.verticalLayout_5.setStretch(1, 10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setStyleSheet("border:none;")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 30)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setStyleSheet("background-color: rgb(37, 64, 83);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 pt \"思源黑体 CN Bold\";\n"
"padding-left:10px;\n"
"border-radius:3px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 7, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setMinimumSize(QtCore.QSize(10, 10))
        self.label_9.setMaximumSize(QtCore.QSize(10, 10))
        self.label_9.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:2px;")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        spacerItem8 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.verticalLayout_8.setStretch(1, 10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_2.setStyleSheet("border:none")
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_7.addWidget(self.textEdit_2)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 30)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        self.label_10.setStyleSheet("background-color: rgb(37, 64, 83);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 pt \"思源黑体 CN Bold\";\n"
"padding-left:10px;\n"
"border-radius:3px;\n"
"")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(0, 7, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setMinimumSize(QtCore.QSize(10, 10))
        self.label_11.setMaximumSize(QtCore.QSize(10, 10))
        self.label_11.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:2px;")
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        spacerItem10 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem10)
        self.verticalLayout_10.setStretch(1, 10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_3.setStyleSheet("border:none")
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_9.addWidget(self.textEdit_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 30)
        self.horizontalLayout_9.setStretch(2, 30)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.verticalLayout_12.addWidget(self.frame_1)

        self.retranslateUi(analyze_form)
        QtCore.QMetaObject.connectSlotsByName(analyze_form)

    def retranslateUi(self, analyze_form):
        _translate = QtCore.QCoreApplication.translate
        analyze_form.setWindowTitle(_translate("analyze_form", "Form"))
        self.label_25.setText(_translate("analyze_form", "数据分析"))
        self.label_2.setText(_translate("analyze_form", "焦虑/抑郁统计图"))
        self.lineEdit_time_3.setPlaceholderText(_translate("analyze_form", "开始日期"))
        self.label_22.setText(_translate("analyze_form", "至"))
        self.lineEdit_time_4.setPlaceholderText(_translate("analyze_form", "结束日期"))
        self.label_17.setText(_translate("analyze_form", "年级："))
        self.label_18.setText(_translate("analyze_form", "班级："))
        self.label_3.setText(_translate("analyze_form", "焦虑数据"))
        self.label_4.setText(_translate("analyze_form", "抑郁数据"))
        self.label_6.setText(_translate("analyze_form", "焦虑结果"))
        self.textEdit.setHtml(_translate("analyze_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_8.setText(_translate("analyze_form", "抑郁结果"))
        self.textEdit_2.setHtml(_translate("analyze_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("analyze_form", "测试方法"))
import db_master_rc
