# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_load_form(object):
    def setupUi(self, load_form):
        load_form.setObjectName("load_form")
        load_form.resize(701, 553)
        load_form.setStyleSheet("#frame {\n"
"    background-color:rgb(70,130,180);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(load_form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(load_form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(210, 90, 291, 251))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/res/载入界面.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(140, 460, 471, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.msg_label = QtWidgets.QLabel(self.frame)
        self.msg_label.setGeometry(QtCore.QRect(140, 400, 431, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg_label.sizePolicy().hasHeightForWidth())
        self.msg_label.setSizePolicy(sizePolicy)
        self.msg_label.setMinimumSize(QtCore.QSize(0, 30))
        self.msg_label.setStyleSheet("font: 75 12pt \"思源黑体 CN Bold\";\n"
"color:white;")
        self.msg_label.setText("")
        self.msg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label.setObjectName("msg_label")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(load_form)
        QtCore.QMetaObject.connectSlotsByName(load_form)

    def retranslateUi(self, load_form):
        _translate = QtCore.QCoreApplication.translate
        load_form.setWindowTitle(_translate("load_form", "Form"))
import db_master_rc
