# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(760, 468)
        login_form.setMinimumSize(QtCore.QSize(760, 468))
        login_form.setMaximumSize(QtCore.QSize(760, 468))
        login_form.setStyleSheet("#frame{\n"
"    border-radius:10px;\n"
"}\n"
"#frame_2{\n"
"    border-image:url(:/icon/res/登录背景.jpg);\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"}\n"
"\n"
"#frame_3{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(login_form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(login_form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.user_edit = QtWidgets.QLineEdit(self.frame_3)
        self.user_edit.setGeometry(QtCore.QRect(60, 140, 421, 34))
        self.user_edit.setStyleSheet("border:1px solid rgba(0,0,0,0.1);\n"
"border-radius:15px;\n"
"padding:1px 10px 1px 10px;")
        self.user_edit.setObjectName("user_edit")
        self.password_edit = QtWidgets.QLineEdit(self.frame_3)
        self.password_edit.setGeometry(QtCore.QRect(60, 200, 421, 34))
        self.password_edit.setStyleSheet("border:1px solid rgba(0,0,0,0.1);\n"
"border-radius:15px;\n"
"padding:1px 10px 1px 10px;")
        self.password_edit.setObjectName("password_edit")
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setGeometry(QtCore.QRect(60, 250, 421, 30))
        self.checkBox.setStyleSheet("    padding-left:22px;\n"
"    padding-right:10px;\n"
"    border-radius:4px;")
        self.checkBox.setObjectName("checkBox")
        self.pb_succeed = QtWidgets.QPushButton(self.frame_3)
        self.pb_succeed.setGeometry(QtCore.QRect(60, 300, 411, 36))
        self.pb_succeed.setStyleSheet("#pushButton_3{\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:18px;\n"
"}\n"
"#pushButton_3:hover{    \n"
"    background-color: #fff;\n"
"    color: rgb(0, 170, 255);\n"
"    border:2px solid rgba(0, 170, 255);\n"
"}\n"
"#pushButton_3:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pb_succeed.setObjectName("pb_succeed")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(140, 60, 240, 51))
        self.label.setStyleSheet("font: 75 20px \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pbhide = QtWidgets.QPushButton(self.frame_3)
        self.pbhide.setGeometry(QtCore.QRect(440, 10, 25, 25))
        self.pbhide.setMinimumSize(QtCore.QSize(25, 25))
        self.pbhide.setMaximumSize(QtCore.QSize(25, 25))
        self.pbhide.setMouseTracking(False)
        self.pbhide.setStyleSheet("border:none;")
        self.pbhide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/登录隐藏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbhide.setIcon(icon)
        self.pbhide.setIconSize(QtCore.QSize(20, 20))
        self.pbhide.setObjectName("pbhide")
        self.pbClose = QtWidgets.QPushButton(self.frame_3)
        self.pbClose.setGeometry(QtCore.QRect(470, 10, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClose.sizePolicy().hasHeightForWidth())
        self.pbClose.setSizePolicy(sizePolicy)
        self.pbClose.setMinimumSize(QtCore.QSize(25, 25))
        self.pbClose.setMaximumSize(QtCore.QSize(25, 25))
        self.pbClose.setMouseTracking(True)
        self.pbClose.setStyleSheet("border:none;")
        self.pbClose.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/登录关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClose.setIcon(icon1)
        self.pbClose.setIconSize(QtCore.QSize(20, 20))
        self.pbClose.setFlat(False)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Form"))
        self.user_edit.setPlaceholderText(_translate("login_form", "请输入用户名"))
        self.password_edit.setPlaceholderText(_translate("login_form", "请输入密码"))
        self.checkBox.setText(_translate("login_form", "记住用户名"))
        self.pb_succeed.setText(_translate("login_form", "登录"))
        self.label.setText(_translate("login_form", "三导脑电精神状态评测系统"))
import db_master_rc
