# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_Form(object):
    def setupUi(self, main_Form):
        main_Form.setObjectName("main_Form")
        main_Form.resize(1173, 1018)
        main_Form.setMinimumSize(QtCore.QSize(0, 90))
        main_Form.setStyleSheet("#main_frame_1{\n"
"    border-image:url(:/icon/res/背景.png);\n"
"}\n"
"\n"
"QToolButton {\n"
"  border: none;\n"
"  font: 75 12pt \"思源黑体 CN Bold\";\n"
"  color:#FFFFFF;\n"
"  background-color: #60A5FA;\n"
"  border-radius: 60px;\n"
"\n"
"  padding-top: 30px; /* 调整上方填充 */\n"
"  padding-bottom: 5px; /* 调整下方填充 */\n"
"  padding-left: 20px; /* 调整左侧填充 */\n"
"  padding-right: 20px; /* 调整右侧填充 */\n"
"\n"
"  qproperty-iconSize: 80px 80px; /* 设置图标大小 */\n"
"  qproperty-toolButtonStyle: ToolButtonTextUnderIcon; /* 设置图标在文字上方 */\n"
" }\n"
"QToolButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-right:3px;\n"
"    padding-bottom:3px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(8, 177, 220);\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color: rgba(95, 120, 140, 100); /* 使用半透明颜色表示禁用状态 */\n"
"    color: rgba(255, 255, 255, 100); /* 同样使用半透明颜色表示禁用状态的文字颜色 */\n"
"}\n"
"#bt1_openDevice {\n"
"  padding-left: 10px; /* 调整左侧填充 */\n"
"  padding-right: 10px; /* 调整右侧填充 */\n"
"}\n"
"#bt2_fileAnaly {\n"
"    padding-top:8px;\n"
"    padding-bottom: 0px;\n"
"    qproperty-iconSize: 35px 35px;\n"
"}\n"
"\n"
"#bt1_openDevice_2{\n"
"    padding-top:10px;\n"
"    padding-bottom: 0px;\n"
"    qproperty-iconSize: 45px 45px;\n"
"}\n"
"#bt_data_analyze_2 {\n"
"    qproperty-iconSize: 50px 50px;\n"
"}")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(main_Form)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.main_frame_1 = QtWidgets.QFrame(main_Form)
        self.main_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame_1.setObjectName("main_frame_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_frame_1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.main_frame_1)
        self.label_2.setMinimumSize(QtCore.QSize(20, 20))
        self.label_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/res/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.main_frame_1)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("庞门正道标题体免费版")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"font: 18pt \"庞门正道标题体免费版\";\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pb_set = QtWidgets.QPushButton(self.main_frame_1)
        self.pb_set.setMinimumSize(QtCore.QSize(25, 25))
        self.pb_set.setMaximumSize(QtCore.QSize(25, 25))
        self.pb_set.setMouseTracking(True)
        self.pb_set.setStyleSheet("QPushButton {\n"
"    background-color: #1E293B;\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pb_set.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_set.setIcon(icon)
        self.pb_set.setIconSize(QtCore.QSize(20, 20))
        self.pb_set.setObjectName("pb_set")
        self.horizontalLayout.addWidget(self.pb_set)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pbhide = QtWidgets.QPushButton(self.main_frame_1)
        self.pbhide.setMinimumSize(QtCore.QSize(25, 25))
        self.pbhide.setMaximumSize(QtCore.QSize(25, 25))
        self.pbhide.setMouseTracking(True)
        self.pbhide.setStyleSheet("QPushButton {\n"
"    background-color: #1E293B;\n"
"    border-radius: 8px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbhide.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbhide.setIcon(icon1)
        self.pbhide.setIconSize(QtCore.QSize(20, 20))
        self.pbhide.setObjectName("pbhide")
        self.horizontalLayout.addWidget(self.pbhide)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pbClose = QtWidgets.QPushButton(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClose.sizePolicy().hasHeightForWidth())
        self.pbClose.setSizePolicy(sizePolicy)
        self.pbClose.setMinimumSize(QtCore.QSize(25, 25))
        self.pbClose.setMaximumSize(QtCore.QSize(25, 25))
        self.pbClose.setMouseTracking(True)
        self.pbClose.setStyleSheet("QPushButton {\n"
"    background-color: #1E293B;\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbClose.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/res/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClose.setIcon(icon2)
        self.pbClose.setIconSize(QtCore.QSize(20, 20))
        self.pbClose.setFlat(False)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout.addWidget(self.pbClose)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(213, 200))
        self.label_5.setMaximumSize(QtCore.QSize(213, 200))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("border-image: url(:/icon/image/img/ea7f384f096232904c0f35dcf53dfc8.bmp);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icon/res/女.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(100, 30))
        self.label_18.setMaximumSize(QtCore.QSize(60, 30))
        self.label_18.setStyleSheet("font: 75 12pt \"思源黑体 CN Bold\";\n"
"color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.comboBox_COM = QtWidgets.QComboBox(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_COM.sizePolicy().hasHeightForWidth())
        self.comboBox_COM.setSizePolicy(sizePolicy)
        self.comboBox_COM.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.horizontalLayout_2.addWidget(self.comboBox_COM)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bt3_infoRecord = QtWidgets.QToolButton(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt3_infoRecord.sizePolicy().hasHeightForWidth())
        self.bt3_infoRecord.setSizePolicy(sizePolicy)
        self.bt3_infoRecord.setMinimumSize(QtCore.QSize(155, 90))
        self.bt3_infoRecord.setMaximumSize(QtCore.QSize(165, 16777215))
        self.bt3_infoRecord.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bt3_infoRecord.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/res/信息录入.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt3_infoRecord.setIcon(icon3)
        self.bt3_infoRecord.setIconSize(QtCore.QSize(80, 80))
        self.bt3_infoRecord.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bt3_infoRecord.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt3_infoRecord.setAutoRaise(False)
        self.bt3_infoRecord.setObjectName("bt3_infoRecord")
        self.horizontalLayout_9.addWidget(self.bt3_infoRecord)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.bt4_dataRecord = QtWidgets.QToolButton(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt4_dataRecord.sizePolicy().hasHeightForWidth())
        self.bt4_dataRecord.setSizePolicy(sizePolicy)
        self.bt4_dataRecord.setMinimumSize(QtCore.QSize(0, 0))
        self.bt4_dataRecord.setMaximumSize(QtCore.QSize(165, 16777215))
        self.bt4_dataRecord.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bt4_dataRecord.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/res/采集第一阶段.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt4_dataRecord.setIcon(icon4)
        self.bt4_dataRecord.setIconSize(QtCore.QSize(80, 80))
        self.bt4_dataRecord.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bt4_dataRecord.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt4_dataRecord.setAutoRaise(False)
        self.bt4_dataRecord.setObjectName("bt4_dataRecord")
        self.horizontalLayout_11.addWidget(self.bt4_dataRecord)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.bt5_dataRecod2 = QtWidgets.QToolButton(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt5_dataRecod2.sizePolicy().hasHeightForWidth())
        self.bt5_dataRecod2.setSizePolicy(sizePolicy)
        self.bt5_dataRecod2.setMinimumSize(QtCore.QSize(155, 90))
        self.bt5_dataRecod2.setMaximumSize(QtCore.QSize(165, 16777215))
        self.bt5_dataRecod2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bt5_dataRecod2.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/res/采集第二阶段.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt5_dataRecod2.setIcon(icon5)
        self.bt5_dataRecod2.setIconSize(QtCore.QSize(80, 80))
        self.bt5_dataRecod2.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bt5_dataRecod2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt5_dataRecod2.setAutoRaise(False)
        self.bt5_dataRecod2.setObjectName("bt5_dataRecod2")
        self.horizontalLayout_12.addWidget(self.bt5_dataRecod2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bt6_generateReport = QtWidgets.QToolButton(self.main_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt6_generateReport.sizePolicy().hasHeightForWidth())
        self.bt6_generateReport.setSizePolicy(sizePolicy)
        self.bt6_generateReport.setMinimumSize(QtCore.QSize(155, 90))
        self.bt6_generateReport.setMaximumSize(QtCore.QSize(165, 16777215))
        self.bt6_generateReport.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bt6_generateReport.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/res/检测报告.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt6_generateReport.setIcon(icon6)
        self.bt6_generateReport.setIconSize(QtCore.QSize(80, 80))
        self.bt6_generateReport.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bt6_generateReport.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt6_generateReport.setAutoRaise(False)
        self.bt6_generateReport.setObjectName("bt6_generateReport")
        self.horizontalLayout_15.addWidget(self.bt6_generateReport)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 15)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line = QtWidgets.QFrame(self.main_frame_1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.listWidget = QtWidgets.QListWidget(self.main_frame_1)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_3.addWidget(self.listWidget)
        self.line_2 = QtWidgets.QFrame(self.main_frame_1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.main_frame_1)
        self.listWidget_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_2.setStyleSheet("")
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_timing = QtWidgets.QLineEdit(self.main_frame_1)
        self.lineEdit_timing.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_timing.setObjectName("lineEdit_timing")
        self.horizontalLayout_4.addWidget(self.lineEdit_timing)
        self.lineEdit_time = QtWidgets.QLineEdit(self.main_frame_1)
        self.lineEdit_time.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.horizontalLayout_4.addWidget(self.lineEdit_time)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 5)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.main_frame_1)

        self.retranslateUi(main_Form)
        QtCore.QMetaObject.connectSlotsByName(main_Form)

    def retranslateUi(self, main_Form):
        _translate = QtCore.QCoreApplication.translate
        main_Form.setWindowTitle(_translate("main_Form", "Form"))
        self.label_3.setText(_translate("main_Form", "精神状态测评系统"))
        self.label_18.setText(_translate("main_Form", "设备号："))
        self.bt3_infoRecord.setText(_translate("main_Form", "信息录入"))
        self.bt4_dataRecord.setText(_translate("main_Form", "数据采集Ⅰ"))
        self.bt5_dataRecod2.setText(_translate("main_Form", "数据采集Ⅱ"))
        self.bt6_generateReport.setText(_translate("main_Form", "检测报告"))
import db_master_rc
