# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_report_Form(object):
    def setupUi(self, report_Form):
        report_Form.setObjectName("report_Form")
        report_Form.resize(899, 953)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(report_Form.sizePolicy().hasHeightForWidth())
        report_Form.setSizePolicy(sizePolicy)
        report_Form.setMinimumSize(QtCore.QSize(899, 950))
        report_Form.setStyleSheet("#frame_1 {\n"
"    background-color: rgb(255,255,255);\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"#frame_9{\n"
"     border-image:url(:/icon/res/蓝色.png);\n"
"}\n"
"\n"
"#frame_top_2 {\n"
"     background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"#frame_2 {\n"
"    background-color: rgb(240,240,240);\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"QTabWidget::pane{\n"
"    margin: 0;\n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab{\n"
"    font-family: \"微软雅黑\";\n"
"     min-width: 130px;\n"
"    min-height: 30px;\n"
"    font-size: 14px;\n"
"    background:rgb(220,220,220);\n"
"    color:black;\n"
"    margin-right: 2px;\n"
"}\n"
"QTabBar::tab:hover{\n"
"    background:#b9e9d9;\n"
"}\n"
"QTabBar::tab:selected{\n"
"    background:#b9e9d9;\n"
"}")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(report_Form)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(report_Form)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_2.sizePolicy().hasHeightForWidth())
        self.frame_top_2.setSizePolicy(sizePolicy)
        self.frame_top_2.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_top_2.setMaximumSize(QtCore.QSize(16777215, 36))
        self.frame_top_2.setSizeIncrement(QtCore.QSize(0, 36))
        self.frame_top_2.setBaseSize(QtCore.QSize(0, 36))
        self.frame_top_2.setMouseTracking(False)
        self.frame_top_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_2.setObjectName("frame_top_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.frame_top_2)
        self.label_8.setMinimumSize(QtCore.QSize(20, 20))
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setStyleSheet("")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/icon/res/logo.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.frame_top_2)
        self.label_3.setMinimumSize(QtCore.QSize(32, 36))
        self.label_3.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"border-radius: 5px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"color: #FFFFFF;\n"
"line-height: 18px;\n"
"font-weight: 400;\n"
"padding-bottom:2px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pbhide_5 = QtWidgets.QPushButton(self.frame_top_2)
        self.pbhide_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pbhide_5.setMaximumSize(QtCore.QSize(25, 25))
        self.pbhide_5.setMouseTracking(False)
        self.pbhide_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbhide_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbhide_5.setIcon(icon)
        self.pbhide_5.setIconSize(QtCore.QSize(20, 20))
        self.pbhide_5.setObjectName("pbhide_5")
        self.horizontalLayout_4.addWidget(self.pbhide_5)
        self.pbClose_5 = QtWidgets.QPushButton(self.frame_top_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClose_5.sizePolicy().hasHeightForWidth())
        self.pbClose_5.setSizePolicy(sizePolicy)
        self.pbClose_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pbClose_5.setMaximumSize(QtCore.QSize(25, 25))
        self.pbClose_5.setMouseTracking(True)
        self.pbClose_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbClose_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClose_5.setIcon(icon1)
        self.pbClose_5.setIconSize(QtCore.QSize(20, 20))
        self.pbClose_5.setFlat(False)
        self.pbClose_5.setObjectName("pbClose_5")
        self.horizontalLayout_4.addWidget(self.pbClose_5)
        self.label_9 = QtWidgets.QLabel(self.frame_top_2)
        self.label_9.setMinimumSize(QtCore.QSize(1, 0))
        self.label_9.setMaximumSize(QtCore.QSize(1, 16777215))
        self.label_9.setMouseTracking(True)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_2.addWidget(self.frame_top_2)
        self.frame_1 = QtWidgets.QFrame(self.frame)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_1)
        self.frame_2.setMinimumSize(QtCore.QSize(160, 0))
        self.frame_2.setStyleSheet("background-color: rgb(94, 124, 138);")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_10.setSpacing(30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setStyleSheet(" QFrame {\n"
"        background-color: transparent;  /* 可选：保持背景透明 */\n"
"        border: none;  /* 其他边框设置为无 */\n"
"        border-bottom: 1px solid white;  /* 仅下方边框为白色1px */\n"
"    }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setStyleSheet("color: white;\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.verticalLayout_10.addWidget(self.frame_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setMaximumSize(QtCore.QSize(10, 50))
        self.label_7.setStyleSheet(" QLabel {\n"
"        background-color: transparent;  /* 设置背景颜色 */\n"
"        border-radius: 4px;  /* 设置圆角半径，值越大圆角越明显 */\n"
"\n"
"    }")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.print_button_3 = QtWidgets.QPushButton(self.frame_5)
        self.print_button_3.setMinimumSize(QtCore.QSize(115, 50))
        self.print_button_3.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: white;\n"
"        font: 75 12pt \"微软雅黑\";\n"
"    }\n"
"QPushButton:hover {\n"
"         background-color: rgba(255, 255, 255, 0.5);\n"
"    }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/res/检测的报告.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_button_3.setIcon(icon2)
        self.print_button_3.setIconSize(QtCore.QSize(25, 25))
        self.print_button_3.setCheckable(True)
        self.print_button_3.setObjectName("print_button_3")
        self.horizontalLayout_3.addWidget(self.print_button_3)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setMaximumSize(QtCore.QSize(10, 50))
        self.label_10.setStyleSheet(" QLabel {\n"
"        background-color: transparent;  /* 设置背景颜色 */\n"
"        border-radius: 4px;  /* 设置圆角半径，值越大圆角越明显 */\n"
"\n"
"    }")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.save_button_3 = QtWidgets.QPushButton(self.frame_8)
        self.save_button_3.setMinimumSize(QtCore.QSize(115, 50))
        self.save_button_3.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: white;\n"
"        font: 75 12pt \"微软雅黑\";\n"
"    }\n"
"QPushButton:hover {\n"
"         background-color: rgba(255, 255, 255, 0.5);\n"
"    }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/res/历史的统计.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button_3.setIcon(icon3)
        self.save_button_3.setIconSize(QtCore.QSize(32, 32))
        self.save_button_3.setCheckable(True)
        self.save_button_3.setObjectName("save_button_3")
        self.horizontalLayout_6.addWidget(self.save_button_3)
        self.verticalLayout.addWidget(self.frame_8)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_4)
        self.tabWidget.setObjectName("tabWidget")

        self.verticalLayout_5.addWidget(self.tabWidget)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.print_button_6 = QtWidgets.QPushButton(self.frame_6)
        self.print_button_6.setMinimumSize(QtCore.QSize(115, 50))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/res/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_button_6.setIcon(icon4)
        self.print_button_6.setIconSize(QtCore.QSize(32, 32))
        self.print_button_6.setObjectName("print_button_6")
        self.horizontalLayout_5.addWidget(self.print_button_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.save_button_6 = QtWidgets.QPushButton(self.frame_6)
        self.save_button_6.setMinimumSize(QtCore.QSize(115, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/res/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button_6.setIcon(icon5)
        self.save_button_6.setIconSize(QtCore.QSize(32, 32))
        self.save_button_6.setObjectName("save_button_6")
        self.horizontalLayout_5.addWidget(self.save_button_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem6)
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 15pt \"微软雅黑\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_23.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.label_4.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\"")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(self.frame_7)
        self.widget.setMinimumSize(QtCore.QSize(0, 360))
        self.widget.setObjectName("widget")
        self.verticalLayout_7.addWidget(self.widget)
        self.textEdit = QtWidgets.QTextEdit(self.frame_7)
        self.textEdit.setStyleSheet("border:none;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.widget_5 = QtWidgets.QWidget(self.frame_7)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_5.setStyleSheet("QWidget{\n"
"    border-bottom: 2px solid rgb(0, 170, 0);\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.label_15.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\"")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        spacerItem9 = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.verticalLayout_7.addWidget(self.widget_5)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_7)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.verticalLayout_7.setStretch(2, 2)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(5, 1)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_1)
        self.verticalLayout_11.addWidget(self.frame)

        self.retranslateUi(report_Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(report_Form)

    def retranslateUi(self, report_Form):
        _translate = QtCore.QCoreApplication.translate
        report_Form.setWindowTitle(_translate("report_Form", "Form"))
        self.label_3.setText(_translate("report_Form", "报告"))
        self.label_6.setText(_translate("report_Form", "个人中心"))
        self.print_button_3.setText(_translate("report_Form", "检测报告"))
        self.save_button_3.setText(_translate("report_Form", "历史统计"))
        self.print_button_6.setText(_translate("report_Form", "打印报告"))
        self.save_button_6.setText(_translate("report_Form", "保存报告"))
        self.label_5.setText(_translate("report_Form", "检测报告"))
        self.label_4.setText(_translate("report_Form", "报告分析"))
        self.textEdit.setHtml(_translate("report_Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_15.setText(_translate("report_Form", "检测报告"))
import db_master_rc
