# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_school_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_school_login(object):
    def setupUi(self, school_login):
        school_login.setObjectName("school_login")
        school_login.resize(481, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(school_login.sizePolicy().hasHeightForWidth())
        school_login.setSizePolicy(sizePolicy)
        school_login.setMinimumSize(QtCore.QSize(481, 650))
        school_login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        school_login.setStyleSheet("#frame_2{\n"
"     background-color: #1E293B;\n"
"    border-radius:10px;\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(school_login)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(school_login)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_top.setMaximumSize(QtCore.QSize(595, 36))
        self.frame_top.setSizeIncrement(QtCore.QSize(0, 36))
        self.frame_top.setBaseSize(QtCore.QSize(0, 36))
        self.frame_top.setMouseTracking(False)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.frame_top)
        self.label_5.setMinimumSize(QtCore.QSize(20, 20))
        self.label_5.setMaximumSize(QtCore.QSize(20, 20))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icon/res/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.frame_top)
        self.label_3.setMinimumSize(QtCore.QSize(32, 36))
        self.label_3.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"border-radius: 5px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"color: #FFFFFF;\n"
"line-height: 18px;\n"
"font-weight: 400;\n"
"padding-bottom:2px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pbhide = QtWidgets.QPushButton(self.frame_top)
        self.pbhide.setMinimumSize(QtCore.QSize(20, 20))
        self.pbhide.setMaximumSize(QtCore.QSize(20, 20))
        self.pbhide.setMouseTracking(True)
        self.pbhide.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbhide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbhide.setIcon(icon)
        self.pbhide.setIconSize(QtCore.QSize(15, 15))
        self.pbhide.setObjectName("pbhide")
        self.horizontalLayout_3.addWidget(self.pbhide)
        self.pbClose = QtWidgets.QPushButton(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClose.sizePolicy().hasHeightForWidth())
        self.pbClose.setSizePolicy(sizePolicy)
        self.pbClose.setMinimumSize(QtCore.QSize(20, 20))
        self.pbClose.setMaximumSize(QtCore.QSize(20, 20))
        self.pbClose.setMouseTracking(True)
        self.pbClose.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbClose.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClose.setIcon(icon1)
        self.pbClose.setIconSize(QtCore.QSize(15, 15))
        self.pbClose.setFlat(False)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout_3.addWidget(self.pbClose)
        self.label_4 = QtWidgets.QLabel(self.frame_top)
        self.label_4.setMinimumSize(QtCore.QSize(1, 0))
        self.label_4.setMaximumSize(QtCore.QSize(1, 16777215))
        self.label_4.setMouseTracking(True)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 58))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 58))
        self.widget_2.setStyleSheet("border-bottom: 2px solid #FFFFFF;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 24px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.widget_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setMinimumSize(QtCore.QSize(0, 58))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(70, 0))
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.comboBox_8 = QtWidgets.QComboBox(self.widget)
        self.comboBox_8.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_8.setObjectName("comboBox_8")
        self.horizontalLayout_11.addWidget(self.comboBox_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setMinimumSize(QtCore.QSize(70, 0))
        self.label_17.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.comboBox_9 = QtWidgets.QComboBox(self.widget)
        self.comboBox_9.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_16.addWidget(self.comboBox_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setMinimumSize(QtCore.QSize(70, 0))
        self.label_18.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.comboBox_10 = QtWidgets.QComboBox(self.widget)
        self.comboBox_10.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout_17.addWidget(self.comboBox_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(70, 0))
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_6.setStyleSheet("font-size: 18px;\n"
"font-family: \"Microsoft YaHei\";color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit.setStyleSheet("border-radius: 2px;\n"
"padding:1px 6px 1px 6px;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(70, 0))
        self.label_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_2.setStyleSheet("border-radius: 2px;\n"
"padding:1px 6px 1px 6px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(70, 0))
        self.label_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setMinimumSize(QtCore.QSize(95, 30))
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_8.addWidget(self.comboBox_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setMinimumSize(QtCore.QSize(70, 0))
        self.label_19.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(95, 30))
        self.lineEdit_3.setStyleSheet("border-radius: 2px;\n"
"padding:1px 6px 1px 6px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_18.addWidget(self.lineEdit_3)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2.addWidget(self.widget)
        spacerItem11 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(198, 38))
        self.pushButton.setStyleSheet("#pushButton{\n"
"background-color: #1E293B;\n"
"font: 75 9pt \"思源黑体 CN Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
" #pushButton:hover{\n"
"    background-color: rgb(8, 177, 220);\n"
"    color: #fff;\n"
"}\n"
"\n"
"#pushButton:pressed\n"
"{\n"
"    background-color:rgb(8, 177, 220);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(198, 38))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"background-color: #1E293B;\n"
"font: 75 9pt \"思源黑体 CN Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
" #pushButton_2:hover{\n"
"    background-color: rgb(8, 177, 220);\n"
"    color: #fff;\n"
"}\n"
"\n"
"#pushButton_2:pressed\n"
"{\n"
"    background-color:rgb(8, 177, 220);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem15 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem15)
        self.verticalLayout_2.setStretch(3, 10)
        self.verticalLayout_2.setStretch(5, 2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.frame)

        self.retranslateUi(school_login)
        QtCore.QMetaObject.connectSlotsByName(school_login)

    def retranslateUi(self, school_login):
        _translate = QtCore.QCoreApplication.translate
        school_login.setWindowTitle(_translate("school_login", "Form"))
        self.label_3.setText(_translate("school_login", "信息录入"))
        self.label.setText(_translate("school_login", "信息录入"))
        self.label_10.setText(_translate("school_login", "学校："))
        self.label_17.setText(_translate("school_login", "年级："))
        self.label_18.setText(_translate("school_login", "班级："))
        self.label_6.setText(_translate("school_login", "学号："))
        self.lineEdit.setPlaceholderText(_translate("school_login", "请输入学号"))
        self.label_7.setText(_translate("school_login", "姓名："))
        self.lineEdit_2.setPlaceholderText(_translate("school_login", "请输入姓名"))
        self.label_8.setText(_translate("school_login", "性别："))
        self.label_19.setText(_translate("school_login", "年龄："))
        self.lineEdit_3.setPlaceholderText(_translate("school_login", "请输入年龄"))
        self.pushButton.setText(_translate("school_login", "取消"))
        self.pushButton_2.setText(_translate("school_login", "确认"))
import db_master_rc
