# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_data_frame(object):
    def setupUi(self, data_frame):
        data_frame.setObjectName("data_frame")
        data_frame.resize(1600, 857)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(data_frame.sizePolicy().hasHeightForWidth())
        data_frame.setSizePolicy(sizePolicy)
        data_frame.setMinimumSize(QtCore.QSize(1600, 857))
        data_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        data_frame.setStyleSheet("#frame_top_2,\n"
"#frame_4,\n"
"#frame_5,\n"
"#frame_top\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"}\n"
"\n"
"\n"
"#frame_top_2 {\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"}\n"
"#frame_4 {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"#frame_5 {\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 160, 180);\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}\n"
"")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(data_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(data_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_top_2 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_2.sizePolicy().hasHeightForWidth())
        self.frame_top_2.setSizePolicy(sizePolicy)
        self.frame_top_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_top_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_top_2.setSizeIncrement(QtCore.QSize(0, 36))
        self.frame_top_2.setBaseSize(QtCore.QSize(0, 36))
        self.frame_top_2.setMouseTracking(False)
        self.frame_top_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_2.setObjectName("frame_top_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_2)
        self.horizontalLayout_4.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.frame_7 = QtWidgets.QFrame(self.frame_top_2)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_14.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setMinimumSize(QtCore.QSize(20, 20))
        self.label_15.setMaximumSize(QtCore.QSize(20, 20))
        self.label_15.setStyleSheet("")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/icon/res/logo.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setStyleSheet("color: white;\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.horizontalLayout_4.addWidget(self.frame_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pbhide = QtWidgets.QPushButton(self.frame_top_2)
        self.pbhide.setMinimumSize(QtCore.QSize(25, 25))
        self.pbhide.setMaximumSize(QtCore.QSize(25, 25))
        self.pbhide.setMouseTracking(False)
        self.pbhide.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbhide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbhide.setIcon(icon)
        self.pbhide.setIconSize(QtCore.QSize(20, 20))
        self.pbhide.setObjectName("pbhide")
        self.horizontalLayout_4.addWidget(self.pbhide)
        self.pbClose = QtWidgets.QPushButton(self.frame_top_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClose.sizePolicy().hasHeightForWidth())
        self.pbClose.setSizePolicy(sizePolicy)
        self.pbClose.setMinimumSize(QtCore.QSize(25, 25))
        self.pbClose.setMaximumSize(QtCore.QSize(25, 25))
        self.pbClose.setMouseTracking(True)
        self.pbClose.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbClose.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClose.setIcon(icon1)
        self.pbClose.setIconSize(QtCore.QSize(20, 20))
        self.pbClose.setFlat(False)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout_4.addWidget(self.pbClose)
        self.label_9 = QtWidgets.QLabel(self.frame_top_2)
        self.label_9.setMinimumSize(QtCore.QSize(1, 0))
        self.label_9.setMaximumSize(QtCore.QSize(1, 16777215))
        self.label_9.setMouseTracking(True)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_6.addWidget(self.frame_top_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(160, 0))
        self.frame_5.setStyleSheet("")
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setSpacing(30)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setMaximumSize(QtCore.QSize(10, 50))
        self.label_7.setStyleSheet(" QLabel {\n"
"        background-color: transparent;  /* 设置背景颜色 */\n"
"        border-radius: 4px;  /* 设置圆角半径，值越大圆角越明显 */\n"
"\n"
"    }")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.print_button_3 = QtWidgets.QPushButton(self.frame_8)
        self.print_button_3.setMinimumSize(QtCore.QSize(115, 50))
        self.print_button_3.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: white;\n"
"        font: 75 12pt \"微软雅黑\";\n"
"    }\n"
"QPushButton:hover {\n"
"         background-color: rgba(255, 255, 255, 0.5);\n"
"    }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/res/检测的报告.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_button_3.setIcon(icon2)
        self.print_button_3.setIconSize(QtCore.QSize(25, 25))
        self.print_button_3.setCheckable(True)
        self.print_button_3.setObjectName("print_button_3")
        self.horizontalLayout_8.addWidget(self.print_button_3)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setMaximumSize(QtCore.QSize(10, 50))
        self.label_16.setStyleSheet(" QLabel {\n"
"        background-color: transparent;  /* 设置背景颜色 */\n"
"        border-radius: 4px;  /* 设置圆角半径，值越大圆角越明显 */\n"
"\n"
"    }")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.save_button_4 = QtWidgets.QPushButton(self.frame_9)
        self.save_button_4.setMinimumSize(QtCore.QSize(115, 50))
        self.save_button_4.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: white;\n"
"        font: 75 12pt \"微软雅黑\";\n"
"    }\n"
"QPushButton:hover {\n"
"         background-color: rgba(255, 255, 255, 0.5);\n"
"    }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/res/历史的统计.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button_4.setIcon(icon3)
        self.save_button_4.setIconSize(QtCore.QSize(32, 32))
        self.save_button_4.setCheckable(True)
        self.save_button_4.setObjectName("save_button_4")
        self.horizontalLayout_15.addWidget(self.save_button_4)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setMaximumSize(QtCore.QSize(10, 50))
        self.label_14.setStyleSheet(" QLabel {\n"
"        background-color: transparent;  /* 设置背景颜色 */\n"
"        border-radius: 4px;  /* 设置圆角半径，值越大圆角越明显 */\n"
"\n"
"    }")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.save_button_3 = QtWidgets.QPushButton(self.frame_10)
        self.save_button_3.setMinimumSize(QtCore.QSize(115, 50))
        self.save_button_3.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: white;\n"
"        font: 75 12pt \"微软雅黑\";\n"
"    }\n"
"QPushButton:hover {\n"
"         background-color: rgba(255, 255, 255, 0.5);\n"
"    }")
        self.save_button_3.setIcon(icon3)
        self.save_button_3.setIconSize(QtCore.QSize(32, 32))
        self.save_button_3.setCheckable(True)
        self.save_button_3.setObjectName("save_button_3")
        self.horizontalLayout_12.addWidget(self.save_button_3)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_16.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_top.setMaximumSize(QtCore.QSize(16777214, 50))
        self.frame_top.setSizeIncrement(QtCore.QSize(0, 36))
        self.frame_top.setBaseSize(QtCore.QSize(0, 36))
        self.frame_top.setMouseTracking(False)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_21.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.frame_top)
        self.label_23.setMinimumSize(QtCore.QSize(50, 0))
        self.label_23.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.comboBox_12 = QtWidgets.QComboBox(self.frame_top)
        self.comboBox_12.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_12.setObjectName("comboBox_12")
        self.horizontalLayout_13.addWidget(self.comboBox_12)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_13)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)
        self.label_19 = QtWidgets.QLabel(self.frame_top)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_21.addWidget(self.label_19)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_20 = QtWidgets.QLabel(self.frame_top)
        self.label_20.setMinimumSize(QtCore.QSize(30, 30))
        self.label_20.setMaximumSize(QtCore.QSize(30, 30))
        self.label_20.setStyleSheet("border: 1px solid white;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px; \n"
"background-color:#FFFFFF;\n"
"")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/icon/res/搜索.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_top)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(120, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_2.setStyleSheet("border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px; ")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout_21.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.label_22 = QtWidgets.QLabel(self.frame_top)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_27 = QtWidgets.QLabel(self.frame_top)
        self.label_27.setMinimumSize(QtCore.QSize(30, 30))
        self.label_27.setMaximumSize(QtCore.QSize(30, 30))
        self.label_27.setStyleSheet("border: 1px solid white;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px; \n"
"background-color:#FFFFFF;\n"
"")
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/icon/res/搜索.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_2.addWidget(self.label_27)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_top)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(120, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_3.setStyleSheet("border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px; ")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.frame_2 = QtWidgets.QFrame(self.frame_top)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_2.setStyleSheet("background-color: rgb(250,250,250);    \n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px; \n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setMinimumSize(QtCore.QSize(30, 30))
        self.label_29.setMaximumSize(QtCore.QSize(30, 30))
        self.label_29.setStyleSheet("border: 1px solid white;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px; \n"
"background-color:#FFFFFF;\n"
"\n"
"")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/icon/res/日历.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_11.addWidget(self.label_29)
        self.lineEdit_time_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_time_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_time_3.setMaximumSize(QtCore.QSize(120, 30))
        self.lineEdit_time_3.setStyleSheet("border:none;\n"
"padding-left: 20px;")
        self.lineEdit_time_3.setObjectName("lineEdit_time_3")
        self.horizontalLayout_11.addWidget(self.lineEdit_time_3)
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setStyleSheet("\n"
"font: 75 9pt \"思源黑体 CN Bold\";")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.lineEdit_time_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_time_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_time_4.setMaximumSize(QtCore.QSize(120, 30))
        self.lineEdit_time_4.setStyleSheet("border:none;\n"
"padding-left: 20px;")
        self.lineEdit_time_4.setText("")
        self.lineEdit_time_4.setObjectName("lineEdit_time_4")
        self.horizontalLayout_11.addWidget(self.lineEdit_time_4)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setMinimumSize(QtCore.QSize(30, 30))
        self.label_32.setMaximumSize(QtCore.QSize(30, 30))
        self.label_32.setStyleSheet("border: 1px solid white;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px; \n"
"background-color:#FFFFFF;")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap(":/icon/res/搜索删除.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32)
        self.horizontalLayout_21.addWidget(self.frame_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.frame_top)
        self.label_17.setMinimumSize(QtCore.QSize(60, 0))
        self.label_17.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.comboBox_9 = QtWidgets.QComboBox(self.frame_top)
        self.comboBox_9.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_6.addWidget(self.comboBox_9)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.frame_top)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_top)
        self.comboBox_10.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout_7.addWidget(self.comboBox_10)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem8)
        self.frame_21 = QtWidgets.QFrame(self.frame_top)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.frame_21)
        self.label_21.setMinimumSize(QtCore.QSize(80, 0))
        self.label_21.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_21)
        self.comboBox_11.setMinimumSize(QtCore.QSize(80, 30))
        self.comboBox_11.setObjectName("comboBox_11")
        self.horizontalLayout_9.addWidget(self.comboBox_11)
        self.horizontalLayout_21.addWidget(self.frame_21)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.frame_23 = QtWidgets.QFrame(self.frame_top)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.frame_23)
        self.label_24.setMinimumSize(QtCore.QSize(80, 0))
        self.label_24.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_23)
        self.comboBox_13.setMinimumSize(QtCore.QSize(80, 30))
        self.comboBox_13.setObjectName("comboBox_13")
        self.horizontalLayout_10.addWidget(self.comboBox_13)
        self.horizontalLayout_21.addWidget(self.frame_23)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem10)
        self.frame_22 = QtWidgets.QFrame(self.frame_top)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"color:rgba(75, 100, 120, 255);\n"
"font: 75 10pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"   background-color: rgb(217,235,249);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"color:rgba(75, 100, 120, 255);\n"
"font: 75 10pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"   background-color: rgb(217,235,249);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout_21.addWidget(self.frame_22)
        self.verticalLayout.addWidget(self.frame_top)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_3)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.frame_bottom_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_bottom_2.sizePolicy().hasHeightForWidth())
        self.frame_bottom_2.setSizePolicy(sizePolicy)
        self.frame_bottom_2.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_bottom_2.setMaximumSize(QtCore.QSize(16777214, 45))
        self.frame_bottom_2.setSizeIncrement(QtCore.QSize(0, 36))
        self.frame_bottom_2.setBaseSize(QtCore.QSize(0, 36))
        self.frame_bottom_2.setMouseTracking(False)
        self.frame_bottom_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_2.setObjectName("frame_bottom_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_bottom_2)
        self.horizontalLayout_5.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_bottom_2)
        self.pushButton_12.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_12.setStyleSheet("QPushButton {color: rgb(255, 255, 255);\n"
"border: none;\n"
"background-color: rgba(255, 255, 255, 0.3);\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-radius:4px;}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        self.label_10 = QtWidgets.QLabel(self.frame_bottom_2)
        self.label_10.setMinimumSize(QtCore.QSize(30, 30))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setStyleSheet("color: rgb(238, 238, 238);\n"
"font: 75 10pt \"微软雅黑\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_bottom_2)
        self.pushButton_13.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_13.setStyleSheet("QPushButton {color: rgb(255, 255, 255);\n"
"border: none;\n"
"background-color: rgba(255, 255, 255, 0.3);\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-radius:4px;}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_5.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_bottom_2)
        self.pushButton_14.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_14.setStyleSheet("QPushButton {color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255, 0.3);\n"
"border-radius:4px;}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_bottom_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{\n"
"color:rgba(75, 100, 120, 255);\n"
"font: 75 10pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"   background-color: rgb(217,235,249);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.label_11 = QtWidgets.QLabel(self.frame_bottom_2)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_bottom_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit.setStyleSheet("border-radius:4px;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.label_12 = QtWidgets.QLabel(self.frame_bottom_2)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_bottom_2)
        self.pushButton_15.setMinimumSize(QtCore.QSize(60, 30))
        self.pushButton_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_15.setStyleSheet("\n"
"QPushButton {color: rgb(255, 255, 255);\n"
"border: none;\n"
"background-color: rgba(255, 255, 255, 0.3);\n"
"font: 75 9pt \"微软雅黑\";\n"
"border-radius:4px;}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(100,160,180);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_5.addWidget(self.pushButton_15)
        self.label_13 = QtWidgets.QLabel(self.frame_bottom_2)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.label_33 = QtWidgets.QLabel(self.frame_bottom_2)
        self.label_33.setMinimumSize(QtCore.QSize(1, 0))
        self.label_33.setMaximumSize(QtCore.QSize(1, 16777215))
        self.label_33.setMouseTracking(True)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_5.addWidget(self.label_33)
        self.verticalLayout.addWidget(self.frame_bottom_2)
        self.horizontalLayout_16.addWidget(self.frame_3)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.frame_6)

        self.retranslateUi(data_frame)
        QtCore.QMetaObject.connectSlotsByName(data_frame)

    def retranslateUi(self, data_frame):
        _translate = QtCore.QCoreApplication.translate
        data_frame.setWindowTitle(_translate("data_frame", "Form"))
        self.label_6.setText(_translate("data_frame", "数据检索"))
        self.print_button_3.setText(_translate("data_frame", "检测列表"))
        self.save_button_4.setText(_translate("data_frame", "异常预警"))
        self.save_button_3.setText(_translate("data_frame", "预约学校"))
        self.label_23.setText(_translate("data_frame", "预约学校："))
        self.label_19.setText(_translate("data_frame", "学号"))
        self.label_22.setText(_translate("data_frame", "姓名"))
        self.lineEdit_time_3.setPlaceholderText(_translate("data_frame", "开始日期"))
        self.label_25.setText(_translate("data_frame", "至"))
        self.lineEdit_time_4.setPlaceholderText(_translate("data_frame", "结束日期"))
        self.label_17.setText(_translate("data_frame", "年级："))
        self.label_18.setText(_translate("data_frame", "班级："))
        self.label_21.setText(_translate("data_frame", "风险程度："))
        self.label_24.setText(_translate("data_frame", "检查状态："))
        self.pushButton_4.setText(_translate("data_frame", "导出本页"))
        self.pushButton_3.setText(_translate("data_frame", "导出列表"))
        self.pushButton_12.setText(_translate("data_frame", "<"))
        self.label_10.setText(_translate("data_frame", "1"))
        self.pushButton_13.setText(_translate("data_frame", ">"))
        self.pushButton_14.setText(_translate("data_frame", "尾页"))
        self.pushButton_5.setText(_translate("data_frame", "导出报告"))
        self.label_11.setText(_translate("data_frame", "跳到"))
        self.label_12.setText(_translate("data_frame", "页"))
        self.pushButton_15.setText(_translate("data_frame", "确定"))
        self.label_13.setText(_translate("data_frame", "共10页"))
import db_master_rc
