# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_patientInfo(object):
    def setupUi(self, patientInfo):
        patientInfo.setObjectName("patientInfo")
        patientInfo.resize(180, 173)
        patientInfo.setStyleSheet("QLabel{\n"
"    font: 75 12pt Microsoft YaHei;\n"
"    color: red;\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(patientInfo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(patientInfo)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(patientInfo)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.us_id = QtWidgets.QLabel(patientInfo)
        self.us_id.setText("")
        self.us_id.setObjectName("us_id")
        self.horizontalLayout.addWidget(self.us_id)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(patientInfo)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.name = QtWidgets.QLabel(patientInfo)
        self.name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name.setTextFormat(QtCore.Qt.PlainText)
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(patientInfo)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.sex = QtWidgets.QLabel(patientInfo)
        self.sex.setObjectName("sex")
        self.horizontalLayout_3.addWidget(self.sex)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(patientInfo)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.age = QtWidgets.QLabel(patientInfo)
        self.age.setText("")
        self.age.setObjectName("age")
        self.horizontalLayout_4.addWidget(self.age)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(patientInfo)
        QtCore.QMetaObject.connectSlotsByName(patientInfo)

    def retranslateUi(self, patientInfo):
        _translate = QtCore.QCoreApplication.translate
        patientInfo.setWindowTitle(_translate("patientInfo", "Form"))
        self.label.setText(_translate("patientInfo", "个人信息"))
        self.label_5.setText(_translate("patientInfo", "学号："))
        self.label_4.setText(_translate("patientInfo", "姓名："))
        self.name.setText(_translate("patientInfo", "-"))
        self.label_2.setText(_translate("patientInfo", "性别："))
        self.sex.setText(_translate("patientInfo", "-"))
        self.label_3.setText(_translate("patientInfo", "年龄："))
