# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_report_item(object):
    def setupUi(self, report_item):
        report_item.setObjectName("report_item")
        report_item.resize(848, 1807)
        report_item.setStyleSheet("#dbmaster_widget{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"    width: 15px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background:  rgb(37, 64, 83);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(report_item)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.dbmaster_widget = QtWidgets.QWidget(report_item)
        self.dbmaster_widget.setObjectName("dbmaster_widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.dbmaster_widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_2 = QtWidgets.QWidget(self.dbmaster_widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 850))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 18pt \"微软雅黑\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setStyleSheet("QWidget{\n"
"    border-bottom: 2px solid rgb(0, 170, 0);\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.label_3.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setMinimumSize(QtCore.QSize(130, 150))
        self.label_4.setMaximumSize(QtCore.QSize(130, 150))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icon/res/人.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setMinimumSize(QtCore.QSize(60, 0))
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setMinimumSize(QtCore.QSize(60, 0))
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setMinimumSize(QtCore.QSize(60, 0))
        self.label_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.label_39 = QtWidgets.QLabel(self.widget_4)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_5.addWidget(self.label_39)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_36 = QtWidgets.QLabel(self.widget_4)
        self.label_36.setMinimumSize(QtCore.QSize(100, 0))
        self.label_36.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_36.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        self.label_38 = QtWidgets.QLabel(self.widget_4)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_38.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_6.addWidget(self.label_38)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_9.setStyleSheet("QWidget{\n"
"    border-bottom: 2px solid rgb(0, 170, 0);\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.widget_9)
        self.label_17.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_44 = QtWidgets.QLabel(self.widget_9)
        self.label_44.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\";")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_7.addWidget(self.label_44)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.widget_11)
        self.label_18.setMinimumSize(QtCore.QSize(150, 0))
        self.label_18.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_18.setStyleSheet("color: rgb(0, 189, 0);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.widget_11)
        self.label_19.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.label_40 = QtWidgets.QLabel(self.widget_11)
        self.label_40.setMinimumSize(QtCore.QSize(150, 0))
        self.label_40.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_40.setStyleSheet("color: rgb(0, 189, 0);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.widget_11)
        self.label_41.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_8.addWidget(self.label_41)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_10)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.widget_12)
        self.label_21.setMinimumSize(QtCore.QSize(110, 0))
        self.label_21.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_21.setStyleSheet("color: rgb(0, 189, 0);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.label_20 = QtWidgets.QLabel(self.widget_12)
        self.label_20.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.label_42 = QtWidgets.QLabel(self.widget_12)
        self.label_42.setMinimumSize(QtCore.QSize(110, 0))
        self.label_42.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_42.setStyleSheet("color: rgb(0, 189, 0);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_9.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.widget_12)
        self.label_43.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 13pt \"微软雅黑\";")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_9.addWidget(self.label_43)
        self.verticalLayout_4.addWidget(self.widget_12)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.widget_13 = QtWidgets.QWidget(self.widget_2)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.widget_13)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_22.setStyleSheet("color: rgb(28, 187, 0);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_23.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.210227 rgba(28, 187, 0, 255), stop:0.721591 rgba(255, 231, 0, 255), stop:1 rgba(255, 17, 17, 255));\n"
"border-radius: 3px;")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setMinimumSize(QtCore.QSize(60, 0))
        self.label_24.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_24.setStyleSheet("color: rgba(255, 17, 17);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.label_25 = QtWidgets.QLabel(self.widget_13)
        self.label_25.setStyleSheet("color: rgb(0, 189, 0);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        self.widget_14.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_26 = QtWidgets.QLabel(self.widget_14)
        self.label_26.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_26.setStyleSheet("color: rgb(0, 189, 0);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_11.addWidget(self.label_26)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.widget_14)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_27.setStyleSheet("background-color: rgba(28, 187, 0, 255);\n"
"border-radius: 3px;")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_6.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.widget_14)
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_6.addWidget(self.label_28)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_29 = QtWidgets.QLabel(self.widget_14)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_29.setStyleSheet("background-color: rgb(164, 208, 6);\n"
"border-radius: 3px;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_7.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.widget_14)
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_7.addWidget(self.label_30)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_31 = QtWidgets.QLabel(self.widget_14)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_31.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 180, 5);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_8.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.widget_14)
        self.label_32.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_8.addWidget(self.label_32)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_33 = QtWidgets.QLabel(self.widget_14)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_33.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 0, 0);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_9.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.widget_14)
        self.label_34.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 12pt \"微软雅黑\";")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_9.addWidget(self.label_34)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addWidget(self.widget_14)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.widget_15 = QtWidgets.QWidget(self.widget_2)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_15.setStyleSheet("QWidget{\n"
"    border-bottom: 2px solid rgb(0, 170, 0);\n"
"}")
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_35 = QtWidgets.QLabel(self.widget_15)
        self.label_35.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\"")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_12.addWidget(self.label_35)
        spacerItem3 = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget_15)
        self.listWidget = QtWidgets.QListWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayout_10.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.dbmaster_widget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_5.setStyleSheet("QWidget{\n"
"    border-bottom: 2px solid rgb(0, 170, 0);\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.label_15.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\"")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        spacerItem4 = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget_5)
        self.label_37 = QtWidgets.QLabel(self.widget)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_37.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 14pt \"思源黑体 CN Bold\";")
        self.label_37.setObjectName("label_37")
        self.verticalLayout.addWidget(self.label_37)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setStyleSheet("border:none;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_45 = QtWidgets.QLabel(self.widget)
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_45.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 14pt \"思源黑体 CN Bold\";")
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setStyleSheet("border:none;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_6.setStyleSheet("QWidget{\n"
"    border-bottom: 2px solid rgb(0, 170, 0);\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_46 = QtWidgets.QLabel(self.widget_6)
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.label_46.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 75 18pt \"微软雅黑\"")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_14.addWidget(self.label_46)
        spacerItem5 = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.widget_6)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        self.textEdit_3.setSizePolicy(sizePolicy)
        self.textEdit_3.setMinimumSize(QtCore.QSize(0, 120))
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textEdit_3.setStyleSheet("border:none;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout.addWidget(self.textEdit_3)
        self.verticalLayout_10.addWidget(self.widget)
        self.verticalLayout_11.addWidget(self.dbmaster_widget)

        self.retranslateUi(report_item)
        QtCore.QMetaObject.connectSlotsByName(report_item)

    def retranslateUi(self, report_item):
        _translate = QtCore.QCoreApplication.translate
        report_item.setWindowTitle(_translate("report_item", "Form"))
        self.label_2.setText(_translate("report_item", "三导脑电抑郁状态评估系统检测报告"))
        self.label_3.setText(_translate("report_item", "基本信息"))
        self.label_6.setText(_translate("report_item", "学号："))
        self.label_5.setText(_translate("report_item", "111"))
        self.label_7.setText(_translate("report_item", "姓名："))
        self.label_8.setText(_translate("report_item", "自行车"))
        self.label_9.setText(_translate("report_item", "性别："))
        self.label_10.setText(_translate("report_item", "男"))
        self.label_11.setText(_translate("report_item", "年龄："))
        self.label_12.setText(_translate("report_item", "111"))
        self.label_13.setText(_translate("report_item", "检查记录："))
        self.label_14.setText(_translate("report_item", "自行车"))
        self.label_36.setText(_translate("report_item", "检查日期："))
        self.label_38.setText(_translate("report_item", "111"))
        self.label_17.setText(_translate("report_item", "抑郁风险"))
        self.label_44.setText(_translate("report_item", "焦虑风险"))
        self.label_18.setText(_translate("report_item", "抑郁风险得分："))
        self.label_19.setText(_translate("report_item", "100分"))
        self.label_40.setText(_translate("report_item", "焦虑风险得分："))
        self.label_41.setText(_translate("report_item", "100分"))
        self.label_21.setText(_translate("report_item", "评估结果："))
        self.label_20.setText(_translate("report_item", "良好"))
        self.label_42.setText(_translate("report_item", "评估结果："))
        self.label_43.setText(_translate("report_item", "良好"))
        self.label_22.setText(_translate("report_item", "0%"))
        self.label_24.setText(_translate("report_item", "100%"))
        self.label_25.setText(_translate("report_item", "评估量程：0 - 100"))
        self.label_26.setText(_translate("report_item", "评估指标："))
        self.label_28.setText(_translate("report_item", "正常 0 - 49"))
        self.label_30.setText(_translate("report_item", "轻度 50 - 64"))
        self.label_32.setText(_translate("report_item", "中度 65 - 74"))
        self.label_34.setText(_translate("report_item", "重度 75 - 100"))
        self.label_35.setText(_translate("report_item", "电极采集信号"))
        self.label_15.setText(_translate("report_item", "温馨提醒"))
        self.label_37.setText(_translate("report_item", "心理方面的状态"))
        self.textEdit.setHtml(_translate("report_item", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_45.setText(_translate("report_item", "生理方面的状态"))
        self.textEdit_2.setHtml(_translate("report_item", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_46.setText(_translate("report_item", "报告阅读说明书"))
        self.textEdit_3.setHtml(_translate("report_item", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import db_master_rc

