# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'right_egg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_right_eeg_form(object):
    def setupUi(self, right_eeg_form):
        right_eeg_form.setObjectName("right_eeg_form")
        right_eeg_form.resize(715, 378)
        right_eeg_form.setStyleSheet("#frame_2 {\n"
"    border:1px solid #ccc;\n"
"    background-color:#000814;\n"
"    }")
        self.verticalLayout = QtWidgets.QVBoxLayout(right_eeg_form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(right_eeg_form)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_2.setStyleSheet("")
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #CBD5E1;\n"
"    border-radius: 15px;\n"
"    font: 75 15pt \"思源黑体 CN Bold\";\n"
"}\n"
"\n"
"QLabel:hover\n"
"{\n"
"    background: #FBBF24;\n"
"    border-radius: 15px;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(right_eeg_form)
        QtCore.QMetaObject.connectSlotsByName(right_eeg_form)

    def retranslateUi(self, right_eeg_form):
        _translate = QtCore.QCoreApplication.translate
        right_eeg_form.setWindowTitle(_translate("right_eeg_form", "Form"))
        self.label_2.setText(_translate("right_eeg_form", "FP1"))
