# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_template_form(object):
    def setupUi(self, template_form):
        template_form.setObjectName("template_form")
        template_form.resize(422, 475)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(template_form.sizePolicy().hasHeightForWidth())
        template_form.setSizePolicy(sizePolicy)
        template_form.setMinimumSize(QtCore.QSize(422, 475))
        template_form.setStyleSheet("#frame{ background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"border-radius:9px;}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(template_form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(template_form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_top.setMaximumSize(QtCore.QSize(595, 36))
        self.frame_top.setSizeIncrement(QtCore.QSize(0, 36))
        self.frame_top.setBaseSize(QtCore.QSize(0, 36))
        self.frame_top.setMouseTracking(False)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.frame_top)
        self.label_5.setMinimumSize(QtCore.QSize(20, 20))
        self.label_5.setMaximumSize(QtCore.QSize(20, 20))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icon/res/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.frame_top)
        self.label_3.setMinimumSize(QtCore.QSize(32, 36))
        self.label_3.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"border-radius: 5px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"color: #FFFFFF;\n"
"line-height: 18px;\n"
"font-weight: 400;\n"
"padding-bottom:2px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pbhide = QtWidgets.QPushButton(self.frame_top)
        self.pbhide.setMinimumSize(QtCore.QSize(20, 20))
        self.pbhide.setMaximumSize(QtCore.QSize(20, 20))
        self.pbhide.setMouseTracking(False)
        self.pbhide.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbhide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbhide.setIcon(icon)
        self.pbhide.setIconSize(QtCore.QSize(15, 15))
        self.pbhide.setObjectName("pbhide")
        self.horizontalLayout_3.addWidget(self.pbhide)
        self.pbClose = QtWidgets.QPushButton(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClose.sizePolicy().hasHeightForWidth())
        self.pbClose.setSizePolicy(sizePolicy)
        self.pbClose.setMinimumSize(QtCore.QSize(20, 20))
        self.pbClose.setMaximumSize(QtCore.QSize(20, 20))
        self.pbClose.setMouseTracking(True)
        self.pbClose.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;  \n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(196,43,28);\n"
"}")
        self.pbClose.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClose.setIcon(icon1)
        self.pbClose.setIconSize(QtCore.QSize(15, 15))
        self.pbClose.setFlat(False)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout_3.addWidget(self.pbClose)
        self.label_4 = QtWidgets.QLabel(self.frame_top)
        self.label_4.setMinimumSize(QtCore.QSize(1, 0))
        self.label_4.setMaximumSize(QtCore.QSize(1, 16777215))
        self.label_4.setMouseTracking(True)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setStyleSheet("border-bottom: 2px solid #FFFFFF;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 24px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setMinimumSize(QtCore.QSize(0, 58))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(70, 0))
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setMinimumSize(QtCore.QSize(70, 0))
        self.label_17.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_16.addWidget(self.lineEdit_2)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setMinimumSize(QtCore.QSize(70, 0))
        self.label_18.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_17.addWidget(self.lineEdit_3)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(198, 38))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"font: 75 9pt \"思源黑体 CN Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
" #pushButton_3:hover{\n"
"    background-color: rgb(8, 177, 220);\n"
"    color: #fff;\n"
"}\n"
"\n"
"#pushButton_3:pressed\n"
"{\n"
"    background-color:rgb(8, 177, 220);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(198, 38))
        self.pushButton.setStyleSheet("#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.988827, y2:0.982955, stop:0 rgba(75, 100, 120, 255), stop:1 rgba(104, 135, 163, 255));\n"
"font: 75 9pt \"思源黑体 CN Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
" #pushButton:hover{\n"
"    background-color: rgb(8, 177, 220);\n"
"    color: #fff;\n"
"}\n"
"\n"
"#pushButton:pressed\n"
"{\n"
"    background-color:rgb(8, 177, 220);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)
        self.verticalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_3.addWidget(self.frame)

        self.retranslateUi(template_form)
        QtCore.QMetaObject.connectSlotsByName(template_form)

    def retranslateUi(self, template_form):
        _translate = QtCore.QCoreApplication.translate
        template_form.setWindowTitle(_translate("template_form", "Form"))
        self.label_3.setText(_translate("template_form", "设置"))
        self.label.setText(_translate("template_form", "学校信息"))
        self.label_10.setText(_translate("template_form", "学校："))
        self.lineEdit.setPlaceholderText(_translate("template_form", "请输入学校"))
        self.label_17.setText(_translate("template_form", "年级："))
        self.lineEdit_2.setPlaceholderText(_translate("template_form", "请输入年级"))
        self.label_18.setText(_translate("template_form", "班级："))
        self.lineEdit_3.setPlaceholderText(_translate("template_form", "请输入班级"))
        self.pushButton_3.setText(_translate("template_form", "取消"))
        self.pushButton.setText(_translate("template_form", "确认"))
import db_master_rc
