#ifndef EEGSENSOR_GLOBAL_H
#define EEGSENSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EEGSENSOR_LIBRARY)
#  define EEGSENSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EEGSENSORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EEGSENSOR_GLOBAL_H
